# Generated by Django 4.2.7 on 2025-11-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Equipo')),
                ('device_type', models.CharField(choices=[('INFUSION_PUMP', 'Bomba de Infusión'), ('VENTILATOR', 'Ventilador'), ('ECG_MACHINE', 'Máquina ECG'), ('MONITOR', 'Monitor de Signos Vitales'), ('DEFIBRILLATOR', 'Desfibrilador'), ('ULTRASOUND', 'Ultrasonido'), ('XRAY', 'Rayos X'), ('MRI', 'Resonancia Magnética'), ('CT_SCANNER', 'Tomógrafo'), ('ANESTHESIA', 'Equipo de Anestesia')], max_length=50, verbose_name='Tipo de Equipo')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Fabricante')),
                ('model_number', models.CharField(max_length=100, verbose_name='Número de Modelo')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('IN_MAINTENANCE', 'En Mantenimiento'), ('IN_REPAIR', 'En Reparación'), ('DECOMMISSIONED', 'Desmantelado'), ('AVAILABLE', 'Disponible'), ('IN_USE', 'En Uso')], default='AVAILABLE', max_length=20, verbose_name='Estado')),
                ('acquisition_date', models.DateField(verbose_name='Fecha de Adquisición')),
                ('warranty_expiration', models.DateField(blank=True, null=True, verbose_name='Vencimiento de Garantía')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Mantenimiento')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Próxima Fecha de Mantenimiento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Equipo Médico',
                'verbose_name_plural': 'Equipos Médicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('CALIBRATION', 'Calibración'), ('INSPECTION', 'Inspección')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('maintenance_date', models.DateField(verbose_name='Fecha de Mantenimiento')),
                ('performed_by', models.CharField(max_length=200, verbose_name='Realizado por')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('next_maintenance_due', models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='medical_devices.device', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento',
                'verbose_name_plural': 'Registros de Mantenimiento',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('MANUAL', 'Manual'), ('WARRANTY', 'Garantía'), ('CERTIFICATE', 'Certificado'), ('INVOICE', 'Factura'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('file_path', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_devices.device', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Documento del Equipo',
                'verbose_name_plural': 'Documentos de Equipos',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='medical_dev_serial__7b9271_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='medical_dev_status_3c3719_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='medical_dev_device__f02da5_idx'),
        ),
    ]
